#!/bin/bash
## Linux 软件源自动换源脚本
## Author: FastMirrors Project
## License: MIT
## 参考: https://github.com/SuperManito/LinuxMirrors

set -e

# 脚本所在目录
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MIRRORS_FILE="${SCRIPT_DIR}/mirrors.txt"

# 颜色定义
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
BLUE='\033[34m'
PLAIN='\033[0m'
BOLD='\033[1m'

SUCCESS="${GREEN}✔${PLAIN}"
ERROR="${RED}✘${PLAIN}"
WARN="${YELLOW}!${PLAIN}"

# 显示帮助信息
show_help() {
    echo -e "${BOLD}Linux 软件源自动换源脚本${PLAIN}"
    echo ""
    echo "用法: $0 [选项]"
    echo ""
    echo "选项:"
    echo "  -l, --list              列出所有可用的镜像源"
    echo "  -s, --set <地址>        设置指定的镜像源地址"
    echo "  -i, --interactive       交互式选择镜像源"
    echo "  -r, --restore           恢复备份的源配置"
    echo "  -c, --current           显示当前软件源配置"
    echo "  -t, --test              测试镜像源连接速度"
    echo "  -u, --update            换源后更新软件包"
    echo "  -h, --help              显示此帮助信息"
    echo ""
    echo "支持的系统:"
    echo "  Debian, Ubuntu, Kali, Deepin, Linux Mint"
    echo "  CentOS, Rocky, AlmaLinux, Fedora"
    echo "  Arch Linux, Manjaro, Alpine"
    echo ""
    echo "示例:"
    echo "  $0 -i                   交互式选择镜像源"
    echo "  $0 -s mirrors.aliyun.com 设置阿里云镜像源"
    echo "  $0 -u                   换源并更新软件包"
    echo ""
}

# 检查 root 权限
check_root() {
    if [[ $EUID -ne 0 ]]; then
        echo -e "${ERROR} 权限不足，请使用 root 权限运行此脚本"
        echo "提示: sudo $0 $@"
        exit 1
    fi
}

# 检测系统类型
detect_system() {
    if [[ -f /etc/os-release ]]; then
        . /etc/os-release
        SYSTEM_ID="${ID}"
        SYSTEM_VERSION_ID="${VERSION_ID}"
        SYSTEM_PRETTY_NAME="${PRETTY_NAME}"
    elif [[ -f /etc/redhat-release ]]; then
        SYSTEM_ID="centos"
        SYSTEM_PRETTY_NAME=$(cat /etc/redhat-release)
    elif [[ -f /etc/arch-release ]]; then
        SYSTEM_ID="arch"
        SYSTEM_PRETTY_NAME="Arch Linux"
    elif [[ -f /etc/alpine-release ]]; then
        SYSTEM_ID="alpine"
        SYSTEM_PRETTY_NAME="Alpine Linux"
    else
        echo -e "${ERROR} 无法检测系统类型"
        exit 1
    fi

    echo -e "${SUCCESS} 检测到系统: ${SYSTEM_PRETTY_NAME}"
}

# 获取系统源文件路径
get_source_file() {
    case "${SYSTEM_ID}" in
        debian|ubuntu|kali|deepin|linuxmint)
            echo "/etc/apt/sources.list"
            ;;
        centos|rhel|rocky|almalinux|fedora)
            echo "/etc/yum.repos.d"
            ;;
        arch|manjaro)
            echo "/etc/pacman.d/mirrorlist"
            ;;
        alpine)
            echo "/etc/apk/repositories"
            ;;
        *)
            echo ""
            ;;
    esac
}

# 备份源配置
backup_source() {
    local source_file="$1"
    local backup_file="${source_file}.bak.$(date +%Y%m%d%H%M%S)"

    if [[ -f "$source_file" ]]; then
        cp "$source_file" "$backup_file"
        echo -e "${SUCCESS} 已备份源配置到: ${backup_file}"
    fi
}

# 列出所有镜像源
list_mirrors() {
    echo -e "${BOLD}可用的 Linux 软件源列表:${PLAIN}"
    echo ""
    local index=1
    while IFS='|' read -r url desc systems || [[ -n "$url" ]]; do
        # 跳过注释行和空行
        [[ "$url" =~ ^#.*$ || -z "$url" ]] && continue
        printf "  ${GREEN}%2d${PLAIN}. %-45s %s\n" "$index" "$url" "$desc"
        ((index++))
    done < "${MIRRORS_FILE}"
    echo ""
}

# 获取镜像源列表数组
get_mirrors_array() {
    local mirrors=()
    while IFS='|' read -r url desc systems || [[ -n "$url" ]]; do
        [[ "$url" =~ ^#.*$ || -z "$url" ]] && continue
        mirrors+=("$url")
    done < "${MIRRORS_FILE}"
    echo "${mirrors[@]}"
}

# Debian/Ubuntu 系换源
change_debian_source() {
    local mirror_url="$1"
    local source_file="/etc/apt/sources.list"

    backup_source "$source_file"

    # 获取系统代号
    local codename
    if [[ "${SYSTEM_ID}" == "ubuntu" ]]; then
        codename=$(lsb_release -cs 2>/dev/null || echo "focal")
    else
        codename=$(cat /etc/os-release | grep VERSION_CODENAME | cut -d= -f2)
    fi

    echo -e "${BLUE}正在生成 ${SYSTEM_ID} 软件源配置...${PLAIN}"

    # 生成 sources.list
    cat > "$source_file" << EOF
# Generated by FastMirrors
# Mirror: ${mirror_url}

deb https://${mirror_url}/ubuntu/ ${codename} main restricted universe multiverse
deb https://${mirror_url}/ubuntu/ ${codename}-updates main restricted universe multiverse
deb https://${mirror_url}/ubuntu/ ${codename}-backports main restricted universe multiverse
deb https://${mirror_url}/ubuntu/ ${codename}-security main restricted universe multiverse
EOF

    echo -e "${SUCCESS} 已更新软件源配置"

    # 更新软件源缓存
    echo -e "${BLUE}正在更新软件源缓存...${PLAIN}"
    apt-get update
    echo -e "${SUCCESS} 软件源缓存更新完成"
}

# CentOS/RHEL 系换源
change_yum_source() {
    local mirror_url="$1"
    local repo_dir="/etc/yum.repos.d"

    # 备份现有配置
    if [[ -d "$repo_dir" ]]; then
        local backup_dir="${repo_dir}.bak.$(date +%Y%m%d%H%M%S)"
        cp -r "$repo_dir" "$backup_dir"
        echo -e "${SUCCESS} 已备份源配置到: ${backup_dir}"
    fi

    # 获取系统版本
    local major_version=$(echo "${SYSTEM_VERSION_ID}" | cut -d. -f1)

    echo -e "${BLUE}正在生成 ${SYSTEM_ID} 软件源配置...${PLAIN}"

    # 根据系统类型生成不同的 repo 文件
    case "${SYSTEM_ID}" in
        centos)
            cat > "${repo_dir}/CentOS-Base.repo" << EOF
[base]
name=CentOS-${major_version} - Base - ${mirror_url}
baseurl=https://${mirror_url}/centos/${major_version}/os/\$basearch/
gpgcheck=1
gpgkey=https://${mirror_url}/centos/RPM-GPG-KEY-CentOS-${major_version}

[updates]
name=CentOS-${major_version} - Updates - ${mirror_url}
baseurl=https://${mirror_url}/centos/${major_version}/updates/\$basearch/
gpgcheck=1
gpgkey=https://${mirror_url}/centos/RPM-GPG-KEY-CentOS-${major_version}

[extras]
name=CentOS-${major_version} - Extras - ${mirror_url}
baseurl=https://${mirror_url}/centos/${major_version}/extras/\$basearch/
gpgcheck=1
gpgkey=https://${mirror_url}/centos/RPM-GPG-KEY-CentOS-${major_version}
EOF
            ;;
        rocky|almalinux)
            cat > "${repo_dir}/${SYSTEM_ID}-Base.repo" << EOF
[baseos]
name=${SYSTEM_PRETTY_NAME} - BaseOS - ${mirror_url}
baseurl=https://${mirror_url}/${SYSTEM_ID}/${major_version}/BaseOS/\$basearch/os/
gpgcheck=1
gpgkey=https://${mirror_url}/${SYSTEM_ID}/RPM-GPG-KEY-${SYSTEM_ID^^}

[appstream]
name=${SYSTEM_PRETTY_NAME} - AppStream - ${mirror_url}
baseurl=https://${mirror_url}/${SYSTEM_ID}/${major_version}/AppStream/\$basearch/os/
gpgcheck=1
gpgkey=https://${mirror_url}/${SYSTEM_ID}/RPM-GPG-KEY-${SYSTEM_ID^^}
EOF
            ;;
    esac

    echo -e "${SUCCESS} 已更新软件源配置"

    # 生成缓存
    echo -e "${BLUE}正在生成软件源缓存...${PLAIN}"
    yum makecache 2>/dev/null || dnf makecache 2>/dev/null
    echo -e "${SUCCESS} 软件源缓存生成完成"
}

# Arch Linux 换源
change_arch_source() {
    local mirror_url="$1"
    local mirrorlist="/etc/pacman.d/mirrorlist"

    backup_source "$mirrorlist"

    echo -e "${BLUE}正在生成 Arch Linux 软件源配置...${PLAIN}"

    cat > "$mirrorlist" << EOF
# Generated by FastMirrors
# Mirror: ${mirror_url}

Server = https://${mirror_url}/archlinux/\$repo/os/\$arch
EOF

    echo -e "${SUCCESS} 已更新软件源配置"

    # 同步软件源
    echo -e "${BLUE}正在同步软件源...${PLAIN}"
    pacman -Sy
    echo -e "${SUCCESS} 软件源同步完成"
}

# Alpine Linux 换源
change_alpine_source() {
    local mirror_url="$1"
    local repos="/etc/apk/repositories"

    backup_source "$repos"

    # 获取 Alpine 版本
    local version=$(cat /etc/alpine-release | cut -d. -f1,2)

    echo -e "${BLUE}正在生成 Alpine Linux 软件源配置...${PLAIN}"

    cat > "$repos" << EOF
# Generated by FastMirrors
# Mirror: ${mirror_url}

https://${mirror_url}/alpine/${version}/main
https://${mirror_url}/alpine/${version}/community
EOF

    echo -e "${SUCCESS} 已更新软件源配置"

    # 更新索引
    echo -e "${BLUE}正在更新软件源索引...${PLAIN}"
    apk update
    echo -e "${SUCCESS} 软件源索引更新完成"
}

# 设置镜像源
set_mirror() {
    local mirror_url="$1"

    if [[ -z "$mirror_url" ]]; then
        echo -e "${ERROR} 请指定镜像源地址"
        exit 1
    fi

    detect_system

    case "${SYSTEM_ID}" in
        debian|ubuntu|kali|deepin|linuxmint)
            change_debian_source "$mirror_url"
            ;;
        centos|rhel|rocky|almalinux|fedora)
            change_yum_source "$mirror_url"
            ;;
        arch|manjaro)
            change_arch_source "$mirror_url"
            ;;
        alpine)
            change_alpine_source "$mirror_url"
            ;;
        *)
            echo -e "${ERROR} 不支持的系统类型: ${SYSTEM_ID}"
            exit 1
            ;;
    esac
}

# 交互式选择镜像源
interactive_select() {
    list_mirrors

    local mirrors=($(get_mirrors_array))
    local count=${#mirrors[@]}

    echo -e "请输入镜像源序号 [1-${count}]，或输入 0 退出:"
    read -r choice

    if [[ "$choice" == "0" ]]; then
        echo "已取消操作"
        exit 0
    fi

    if [[ ! "$choice" =~ ^[0-9]+$ ]] || [[ "$choice" -lt 1 ]] || [[ "$choice" -gt "$count" ]]; then
        echo -e "${ERROR} 无效的选择"
        exit 1
    fi

    local selected_mirror="${mirrors[$((choice-1))]}"
    echo -e "${BLUE}您选择了: ${selected_mirror}${PLAIN}"

    set_mirror "$selected_mirror"
}

# 显示当前配置
show_current() {
    detect_system
    local source_file=$(get_source_file)

    echo -e "${BOLD}当前软件源配置:${PLAIN}"
    echo ""

    if [[ -f "$source_file" ]]; then
        cat "$source_file"
    elif [[ -d "$source_file" ]]; then
        echo "源配置目录: ${source_file}"
        echo ""
        for repo in "$source_file"/*.repo; do
            if [[ -f "$repo" ]]; then
                echo -e "${GREEN}=== $(basename $repo) ===${PLAIN}"
                cat "$repo"
                echo ""
            fi
        done
    else
        echo "未找到源配置文件"
    fi
}

# 测试镜像源速度
test_mirrors() {
    echo -e "${BOLD}测试镜像源连接速度...${PLAIN}"
    echo ""

    local mirrors=($(get_mirrors_array))
    local results=()

    for mirror in "${mirrors[@]}"; do
        echo -n "测试 ${mirror}... "
        local start_time=$(date +%s%N)
        if curl -s --connect-timeout 3 "https://${mirror}/" > /dev/null 2>&1; then
            local end_time=$(date +%s%N)
            local duration=$(( (end_time - start_time) / 1000000 ))
            echo -e "${GREEN}${duration}ms${PLAIN}"
            results+=("${duration}|${mirror}")
        else
            echo -e "${RED}超时${PLAIN}"
            results+=("999999|${mirror}")
        fi
    done

    # 排序并显示结果
    echo ""
    echo -e "${BOLD}镜像源速度排名 (从快到慢):${PLAIN}"
    IFS=$'\n' sorted=($(sort -t'|' -k1 -n <<<"${results[*]}"))
    unset IFS

    local rank=1
    for result in "${sorted[@]}"; do
        local time=$(echo "$result" | cut -d'|' -f1)
        local mirror=$(echo "$result" | cut -d'|' -f2)
        if [[ "$time" == "999999" ]]; then
            printf "  %2d. %-45s ${RED}不可用${PLAIN}\n" "$rank" "$mirror"
        else
            printf "  %2d. %-45s ${GREEN}%sms${PLAIN}\n" "$rank" "$mirror" "$time"
        fi
        ((rank++))
    done
}

# 更新软件包
update_packages() {
    detect_system

    echo -e "${BLUE}正在更新软件包...${PLAIN}"

    case "${SYSTEM_ID}" in
        debian|ubuntu|kali|deepin|linuxmint)
            apt-get update && apt-get upgrade -y
            ;;
        centos|rhel|rocky|almalinux|fedora)
            yum update -y 2>/dev/null || dnf update -y 2>/dev/null
            ;;
        arch|manjaro)
            pacman -Syu --noconfirm
            ;;
        alpine)
            apk update && apk upgrade
            ;;
    esac

    echo -e "${SUCCESS} 软件包更新完成"
}

# 主函数
main() {
    local action=""
    local mirror_url=""

    # 解析参数
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -l|--list)
                action="list"
                shift
                ;;
            -s|--set)
                action="set"
                mirror_url="$2"
                shift 2
                ;;
            -i|--interactive)
                action="interactive"
                shift
                ;;
            -r|--restore)
                action="restore"
                shift
                ;;
            -c|--current)
                action="current"
                shift
                ;;
            -t|--test)
                action="test"
                shift
                ;;
            -u|--update)
                action="update"
                shift
                ;;
            -h|--help)
                show_help
                exit 0
                ;;
            *)
                echo -e "${ERROR} 未知选项: $1"
                show_help
                exit 1
                ;;
        esac
    done

    # 默认显示帮助
    if [[ -z "$action" ]]; then
        show_help
        exit 0
    fi

    # 执行操作
    case "$action" in
        list)
            list_mirrors
            ;;
        set)
            check_root
            set_mirror "$mirror_url"
            ;;
        interactive)
            check_root
            interactive_select
            ;;
        current)
            show_current
            ;;
        test)
            test_mirrors
            ;;
        update)
            check_root
            set_mirror "$mirror_url"
            update_packages
            ;;
    esac
}

main "$@"
